sudo: required
services:
    - docker

before_install:
    - docker build -t santanurahaman/docker-react-helloworld -f Dockerfile.dev .

script:
    - docker run -e CI=true santanurahaman/docker-react-helloworld npm run test -- --coverage